name: Gatsby Publish

on:
  push:
    branches:
      - master
env:
  NPM_CONFIG_LEGACY_PEER_DEPS: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          node-version: ${{ matrix.node-version }}
          deploy-branch: gh-pages