name: Gatsby Publish

on:
  push:
    branches:
      - master
env:
  NPM_CONFIG_LEGACY_PEER_DEPS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
        node-version: 18
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages